steps:
- name: 'node:20'
  script: |
    npm install -g npm@9.0.0 && \
    npm ci && \
    npm run build
  env:
  - 'GOOGLE_MAPS_KEY=${_GOOGLE_MAPS_KEY}'
  - 'HOST=${_HOST}'
  - 'STATIC_HOST=${_STATIC_HOST}'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gsutil'
    - '-m'
    - 'rsync'
    - '-r'
    - 'dist/'
    - '${_WWW_BUCKET}/'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gsutil -m setmeta \
        -h 'Cache-Control:no-cache,max-age=0,must-revalidate' \
        '${_WWW_BUCKET}/manifest.json' \
        '${_WWW_BUCKET}/auto-loader.js' \
        '${_WWW_BUCKET}/loader.js'
